services:
  flask:
    image: cr.yandex/crpj07mj889kvh8ss9gs/xo:latest
    container_name: xo
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=johnalen
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - VIRTUAL_HOST=johnalen.ru,www.johnalen.ru
      - LETSENCRYPT_HOST=johnalen.ru,www.johnalen.ru
      - LETSENCRYPT_EMAIL=mozarko@yandex.ru
    working_dir: /app
    command: gunicorn -w 1 -b 0.0.0.0:5000 app:app

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: johnalen
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:rw
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: mozarko@yandex.ru
    volumes:
      - /etc/nginx/certs:/etc/nginx/certs:rw
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  pgdata:
