services:
  flask:
    build: .
    container_name: xo
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=johnalen
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./src:/app
    working_dir: /app
    command: python3 app.py

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: johnalen
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
