services:
  flask:
    build: .
    container_name: xo
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=johnalen
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./src:/app
    working_dir: /app
    command: python3 app.py

  celery:
    build: .
    container_name: celery_worker
    restart: always
    depends_on:
      - flask
      - redis
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=johnalen
      - SECRET_KEY=${SECRET_KEY}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./src:/app
    working_dir: /app
    command: celery -A celery_worker.celery_app worker --loglevel=info

  redis:
    image: redis:7
    container_name: redis
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: johnalen
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
