"""initial

Revision ID: 13e63b21da8b
Revises: 
Create Date: 2025-06-03 19:12:20.810534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e63b21da8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC-7', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC-7', NOW())"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('board', sa.String(), nullable=False),
    sa.Column('player_symbol', sa.String(), nullable=False),
    sa.Column('computer_symbol', sa.String(), nullable=True),
    sa.Column('winner', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('computer_first_move', sa.Boolean(), nullable=True),
    sa.Column('is_game_over', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(), nullable=False),
    sa.Column('multiplayer', sa.Boolean(), nullable=False),
    sa.Column('player2_symbol', sa.String(), nullable=True),
    sa.Column('user2_id', sa.Integer(), nullable=True),
    sa.Column('user2_login', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC-7', NOW())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('UTC-7', NOW())"), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
